meta_product_name: "RentEase"
meta_title: "RentEase - GÃ©rez vos biens locatifs comme un professionnel ! ğŸ "
meta_description: "RentEase est un outil clÃ© en main qui permet aux propriÃ©taires de mieux gÃ©rer leur bail de location. Pilotez vos locations de maniÃ¨res professionnelles sans passer par des intermÃ©diaires onÃ©reux. Gardez un oeil sur votre comptabilitÃ© et investissez de maniÃ¨re astucieuse !"
meta_image: "logo.svg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
